name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        job:
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-gnu
          # - os: windows-latest
          #   arch: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.job.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.arch }}
          components: rustfmt, clippy

      - name: Install dependencies
        if: matrix.job.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
          sudo apt-get install -y gdal-bin
          ogrinfo --version

      - name: Check formatting
        run: cargo fmt --check

      - name: Run test
        run: cargo test

      - name: Run clippy
        run: cargo clippy
